### ISSUE TITLE
恳请请教，Froze ERROR！

### ISSUE THREAD

**Issue by cainiaoyexiangfei** [PanJinquan/tensorflow_models_nets#1]
想跟你请教，根据你的方法或代码保存后，我再导入后缀为meta图并赋予ckpt中的参数，是可以正常跑预测的。但是forzen为pb文件时就报‘INFO:tensorflow:Froze 0 variables.INFO:tensorflow:Converted 0 variables to const ops.’，并且，导入pb文件，再运用预测就会报缺少XX之类的错误。恳请指教，谢谢！

**Comment by Peony-Wang** [comment]
你好，请问后来你有解决这个问题吗？我也有同样的需要，恳请指教！
